# Generated by Django 4.0.6 on 2022-08-01 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pur_qty', models.FloatField(default=0)),
                ('sale_qty', models.FloatField(default=0)),
                ('total_bal', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.purchase')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sale')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
            },
        ),
    ]
