# Generated by Django 4.0.6 on 2022-08-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_inventory_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='short_name',
            field=models.CharField(max_length=50),
        ),
    ]
