# Generated by Django 4.0.6 on 2022-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_vendor_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='total_amt',
            field=models.FloatField(editable=False),
        ),
    ]
