# Generated by Django 4.0.6 on 2022-08-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customer_remove_inventory_total_bal_qty_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': '7.Customers'},
        ),
    ]
