# Generated by Django 4.0.6 on 2022-08-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_inventory_pur_qty_alter_inventory_purchase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='total_bal',
            new_name='total_bal_qty',
        ),
    ]
